version: '3'
services:
  reactui:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: reactui
    stdin_open: true
    volumes:
       - ./:/usr/src/app/
       - /usr/src/app/node_modules
