version: '3'
services:
  front:
    build:
      context: './'  #foldername
      dockerfile: Dockerfile
    ports:
      -3000:3000
    container_name: react-chat-app
    networks:
      - mern-stack-networks
    volumes:
      - ./:/app #folder map to app
networks:
  mern-stack-network:
volumes:
  ./:/app

